#!/usr/bin/env node
/**
 * Generates public/sitemap.xml and public/robots.txt from seo.config.json.
 *
 *   node seo/sitemap.mjs                    # every URL that resolves to a page
 *   node seo/sitemap.mjs --include-catalog  # force every /song/* and /artist/* URL
 *   node seo/sitemap.mjs --dry-run
 *
 * A URL earns its place in the sitemap by resolving to a real page on disk:
 * index.html for `/`, or a pre-rendered public/<route>/index.html written by
 * `npm run seo:prerender`. Routes that are only SPA state (/search, /likes,
 * /premium — there is no router yet) are left out rather than fed to Search
 * Console as soft 404s. --include-catalog overrides the check for the case
 * where the server renders those routes itself.
 */
import { mkdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { artistPath, artistsOf, loadCatalog, loadConfig, ROOT, slug, songPath } from './lib/site.mjs';

/** True when a route resolves to a page on disk (pre-rendered, built or root). */
export async function routeResolves(routePath, root = ROOT) {
  const rel = routePath.replace(/^\/+|\/+$/g, '');
  const candidates = rel
    ? [path.join(root, 'dist', rel, 'index.html'), path.join(root, 'public', rel, 'index.html')]
    : [path.join(root, 'dist/index.html'), path.join(root, 'index.html')];
  for (const file of candidates) {
    if (await stat(file).then((s) => s.isFile(), () => false)) return true;
  }
  return false;
}

const xmlEscape = (value) =>
  String(value).replace(/[<>&'"]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;' })[c]);

export async function buildSitemap({ includeCatalog = false, root = ROOT } = {}) {
  const config = await loadConfig();
  const songs = await loadCatalog();
  const { origin } = config.site;
  const today = new Date().toISOString().slice(0, 10);

  const candidates = config.routes.map((route) => ({
    path: route.path,
    priority: route.priority,
    changefreq: route.changefreq,
    always: false,
  }));

  for (const song of songs) {
    candidates.push({
      path: songPath(song),
      priority: song.trending ? 0.8 : 0.6,
      changefreq: 'weekly',
      always: includeCatalog,
    });
  }
  for (const artist of artistsOf(songs).keys()) {
    candidates.push({ path: artistPath(artist), priority: 0.6, changefreq: 'weekly', always: includeCatalog });
  }
  for (const language of new Set(songs.map((s) => s.language))) {
    candidates.push({
      path: `/language/${slug(language)}`,
      priority: 0.7,
      changefreq: 'weekly',
      always: includeCatalog,
    });
  }

  const entries = [];
  const seen = new Set();
  const skipped = [];
  for (const candidate of candidates) {
    if (seen.has(candidate.path)) continue;
    seen.add(candidate.path);
    if (!candidate.always && !(await routeResolves(candidate.path, root))) {
      skipped.push(candidate.path);
      continue;
    }
    entries.push({ loc: origin + candidate.path, priority: candidate.priority, changefreq: candidate.changefreq });
  }

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries.map((e) =>
      [
        '  <url>',
        `    <loc>${xmlEscape(e.loc)}</loc>`,
        `    <lastmod>${today}</lastmod>`,
        `    <changefreq>${e.changefreq}</changefreq>`,
        `    <priority>${e.priority.toFixed(1)}</priority>`,
        '  </url>',
      ].join('\n'),
    ),
    '</urlset>',
    '',
  ].join('\n');

  const robots = [
    '# robots.txt — generated by `npm run seo:sitemap`',
    'User-agent: *',
    'Allow: /',
    '',
    '# Player state and search result URLs add no index value',
    'Disallow: /*?q=',
    'Disallow: /*&play=',
    '',
    'User-agent: GPTBot',
    'Allow: /',
    '',
    'User-agent: PerplexityBot',
    'Allow: /',
    '',
    `Sitemap: ${origin}/sitemap.xml`,
    '',
  ].join('\n');

  return { xml, robots, entries, skipped };
}

async function main(argv) {
  const { xml, robots, entries, skipped } = await buildSitemap({ includeCatalog: argv.includes('--include-catalog') });

  if (argv.includes('--dry-run')) {
    console.log(xml);
    console.log(robots);
    return;
  }

  await mkdir(path.join(ROOT, 'public'), { recursive: true });
  await writeFile(path.join(ROOT, 'public/sitemap.xml'), xml);
  await writeFile(path.join(ROOT, 'public/robots.txt'), robots);
  console.log(`public/sitemap.xml written (${entries.length} URLs)`);
  console.log('public/robots.txt written');
  if (skipped.length) {
    console.log(`left out — no page on disk yet: ${skipped.join(', ')}`);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main(process.argv.slice(2)).catch((err) => {
    console.error(`seo:sitemap failed — ${err.message}`);
    process.exitCode = 1;
  });
}
