#!/usr/bin/env node
/**
 * Generates public/sitemap.xml and public/robots.txt from seo.config.json.
 *
 *   node seo/sitemap.mjs                    # the routes the app actually serves
 *   node seo/sitemap.mjs --include-catalog  # adds /song/* and /artist/* URLs
 *   node seo/sitemap.mjs --dry-run
 *
 * Catalogue URLs stay opt-in: listing routes the SPA does not serve yet would
 * feed Search Console a wall of soft 404s.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { artistPath, artistsOf, loadCatalog, loadConfig, ROOT, songPath } from './lib/site.mjs';

const xmlEscape = (value) =>
  String(value).replace(/[<>&'"]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;' })[c]);

export async function buildSitemap({ includeCatalog = false } = {}) {
  const config = await loadConfig();
  const { origin } = config.site;
  const today = new Date().toISOString().slice(0, 10);

  const entries = config.routes.map((route) => ({
    loc: origin + route.path,
    priority: route.priority,
    changefreq: route.changefreq,
  }));

  if (includeCatalog) {
    const songs = await loadCatalog();
    for (const song of songs) {
      entries.push({ loc: origin + songPath(song), priority: song.trending ? 0.8 : 0.6, changefreq: 'weekly' });
    }
    for (const artist of artistsOf(songs).keys()) {
      entries.push({ loc: origin + artistPath(artist), priority: 0.6, changefreq: 'weekly' });
    }
  }

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries.map((e) =>
      [
        '  <url>',
        `    <loc>${xmlEscape(e.loc)}</loc>`,
        `    <lastmod>${today}</lastmod>`,
        `    <changefreq>${e.changefreq}</changefreq>`,
        `    <priority>${e.priority.toFixed(1)}</priority>`,
        '  </url>',
      ].join('\n'),
    ),
    '</urlset>',
    '',
  ].join('\n');

  const robots = [
    '# robots.txt — generated by `npm run seo:sitemap`',
    'User-agent: *',
    'Allow: /',
    '',
    '# Player state and search result URLs add no index value',
    'Disallow: /*?q=',
    'Disallow: /*&play=',
    '',
    'User-agent: GPTBot',
    'Allow: /',
    '',
    'User-agent: PerplexityBot',
    'Allow: /',
    '',
    `Sitemap: ${origin}/sitemap.xml`,
    '',
  ].join('\n');

  return { xml, robots, entries };
}

async function main(argv) {
  const { xml, robots, entries } = await buildSitemap({ includeCatalog: argv.includes('--include-catalog') });

  if (argv.includes('--dry-run')) {
    console.log(xml);
    console.log(robots);
    return;
  }

  await mkdir(path.join(ROOT, 'public'), { recursive: true });
  await writeFile(path.join(ROOT, 'public/sitemap.xml'), xml);
  await writeFile(path.join(ROOT, 'public/robots.txt'), robots);
  console.log(`public/sitemap.xml written (${entries.length} URLs)`);
  console.log('public/robots.txt written');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main(process.argv.slice(2)).catch((err) => {
    console.error(`seo:sitemap failed — ${err.message}`);
    process.exitCode = 1;
  });
}
